### ISSUE TITLE
Install errors and warnings with `yarn install`

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-front-end-template#170]
running `yarn install` for this repo on a fresh machine (both ubuntu and fedora tested) with yarn just installed, I get this _non-breaking_ error and warning info: 
 
```
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @polkadot/ui-settings@0.69.1" has unmet peer dependency "@polkadot/networks@*".
warning " > eslint-plugin-import@2.22.1" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.20.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > eslint-config-semistandard@15.0.1" has unmet peer dependency "eslint@>=6.0.1".
warning " > eslint-config-standard@16.0.2" has unmet peer dependency "eslint@^7.12.1".
warning " > eslint-plugin-node@11.1.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@3.0.1" has unmet peer dependency "eslint@>=4.19.1".
warning " > eslint-plugin-standard@5.0.0" has unmet peer dependency "eslint@>=5.0.0".
[5/5] Building fresh packages...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[4/8] ⡀ usb-detection
warning Error running install script for optional dependency: "/home/nuke/git/substrate-front-end-template/node_modules/usb-detection: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/nuke/git/substrate-front-end-template/node_modules/usb-detection
Output:
prebuild-install WARN install connect ETIMEDOUT 140.82.113.4:443
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.14.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at \"/usr/bin/python3\"
gyp http GET https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nuke/git/substrate-front-end-template/node_modules/usb-detection/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nuke/.cache/node-gyp/15.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/nuke/.cache/node-gyp/15.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/nuke/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/nuke/git/substrate-front-end-template/node_modules/usb-detection',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.4.0-71-generic
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/nuke/git/substrate-front-end-template/node_modules/usb-detection
Done in 214.92s.
```

A `yarn start` works as expected, and a `yarn install` again gives no errors and no changes... 🤷🏼

**Comment by Joe-mcgee** [comment]
hmm node-gyp error on a ubuntu machine ```sudo apt-get install build-essential```?

**Comment by NukeManDan** [comment]
That could be it indeed @Joe-mcgee , I removed this in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/972  - but it is not breaking the use of the frontend... so it is unclear _why_ this is needed.

**Comment by Joe-mcgee** [comment]
I was content believing some npm package was perhaps using a C library to optimise a part of their code, and the lack of the C compiler simply made it fallback on its native impl.

Looking closer though is doubly strange, the package 'usb-detect' why would something like this be needed for a frontend template? Kind of gives me bid vibes actually, especially since its not holding up the program, feels like an injection than a dependency.  I haven't looked closely though, perhaps just a bit of paranoia

**Comment by jimmychu0807** [comment]
Front-end template depends on polkadot-js-api which contains [@polkadot/hw-ledger](https://www.npmjs.com/package/@polkadot/hw-ledger) that depends on usb-detection. I believe it may relate to polkadot-js-api being able to read USB h/w wallet. 

I don't think this is an issue per se, just that the machine doesn't have its prerequisite installed. Closing this for now. Feel free to re-open this if you strongly believe otherwise.
