### ISSUE TITLE
Yarn install issue with yarn-berry.cjs

### ISSUE THREAD

**Issue by andreaturli** [substrate-developer-hub/substrate-front-end-template#177]
Following https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup#install-the-front-end-template

Using 
```
❯ npm -version
6.4.1
```

and

```
❯ npm install --global yarn


> yarn@1.22.10 preinstall /Users/andrea/.nvm/versions/node/v8.14.0/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/Users/andrea/.nvm/versions/node/v8.14.0/bin/yarn -> /Users/andrea/.nvm/versions/node/v8.14.0/lib/node_modules/yarn/bin/yarn.js
/Users/andrea/.nvm/versions/node/v8.14.0/bin/yarnpkg -> /Users/andrea/.nvm/versions/node/v8.14.0/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.10
updated 1 package in 0.964s
```
```
❯ yarn install
/my/folder/substrate/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:2
module.exports=(()=>{var e={25545:e=>{function t(e){var t=new Error("Cannot find module '"+e+"'");throw t.code="MODULE_NOT_FOUND",t}t.keys=()=>[],t.resolve=t,t.id=25545,e.exports=t},44692:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>g});var A=r(54143);const n={optional:!0},o=[["@samverschueren/stream-to-observable@<0.3.1",{peerDependenciesMeta:{rxjs:n,zenObservable:n}}],["any-observable@<0.5.1",{peerDependenciesMeta:{rxjs:n,zenObservable:n}}],["@pm2/agent@<1.0.4",{dependencies:{debug:"*"}}],["debug@<4.2.0",{peerDependenciesMeta:{"supports-color":n}}],["got@<11",{dependencies:{"@types/responselike":"^1.0.0","@types/keyv":"^3.1.1"}}],["cacheable-lookup@<4.1.2",{dependencies:{"@types/keyv":"^3.1.1"}}],["http-link-dataloader@*",{peerDependencies:{graphql:"^0.13.1 || ^14.0.0"}}],["typescript-language-server@*",{dependencies:{"vscode-jsonrpc":"^5.0.1","vscode-languageserver-protocol":"^3.15.0"}}],["postcss-s

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by lmatz** [comment]
I encounter the same issue with `node` and `npm` installed via `apt-get` and `yarn` installed via `npm`. Then I changed to pre-compiled binary for `nodejs` via the official website and installed the `yarn`, and no problem this time.

**Comment by NukeManDan** [comment]
so it's that yarn v2 works, but yarn v1 is causing issues here?
