### ISSUE TITLE
yarn install fails for v3.0.0+monthly-2021-05

### ISSUE THREAD

**Issue by gww-parity** [substrate-developer-hub/substrate-front-end-template#183]
`yarn install` fails for f9840705c9571b1bc92dc6181e6d44d093ee9fd5:

As in `README.md` :

```
git clone https://github.com/substrate-developer-hub/substrate-front-end-template.git
cd substrate-front-end-template
yarn install
```

results in:

```
Cloning into 'substrate-front-end-template'...
remote: Enumerating objects: 3573, done.
remote: Counting objects: 100% (1691/1691), done.
remote: Compressing objects: 100% (1676/1676), done.
remote: Total 3573 (delta 20), reused 1668 (delta 9), pack-reused 1882
Receiving objects: 100% (3573/3573), 113.50 MiB | 10.60 MiB/s, done.
Resolving deltas: 100% (1163/1163), done.
➤ YN0000: ┌ Resolution step
➤ YN0002: │ react-dev-utils@npm:11.0.4 doesn't provide typescript (p79ddf), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:11.0.4 doesn't provide webpack (p2af19), requested by fork-ts-checker-webpack-plugin
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 312ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:18.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:13.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ bip32-ed25519@https://github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134 can't be found in the cache
➤ YN0058: │ bip32-ed25519@https://github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: Packing the package failed (exit code 1, logs can be found here: /tmp/xfs-e7af11dd/pack.log)
➤ YN0000: └ Completed in 5s 175ms
➤ YN0000: Failed with errors in 5s 492ms
```

where log file:

```
$ cat /tmp/xfs-e7af11dd/pack.log
Installing the project using npm

npm ERR! semver.simplifyRange is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2021-06-30T21_10_17_557Z-debug.log
```

where complete log:

```
$ cat /home/.../.npm/_logs/2021-06-30T21_10_17_557Z-debug.log

0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.17.0
2 info using node@v16.4.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/tmp/xfs-9c036f85/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/.../.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 timing npm:load:configload Completed in 6ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 8ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 51ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 timing idealTree:#root Completed in 1ms
32 timing idealTree:buildDeps Completed in 1ms
33 timing idealTree:fixDepFlags Completed in 0ms
34 timing idealTree Completed in 52ms
35 timing reify:loadTrees Completed in 58ms
36 timing reify:diffTrees Completed in 2ms
37 silly reify moves {}
38 timing reify:retireShallow Completed in 0ms
39 timing reify:createSparse Completed in 4ms
40 timing reify:loadBundles Completed in 0ms
41 silly audit bulk request {
41 silly audit   'balanced-match': [ '1.0.0' ],
41 silly audit   'bn.js': [ '5.1.1', '4.11.8' ],
41 silly audit   'brace-expansion': [ '1.1.11' ],
41 silly audit   brorand: [ '1.1.0' ],
41 silly audit   'browser-stdout': [ '1.3.0' ],
41 silly audit   commander: [ '2.9.0' ],
41 silly audit   'concat-map': [ '0.0.1' ],
41 silly audit   debug: [ '2.6.8' ],
41 silly audit   diff: [ '3.2.0' ],
41 silly audit   elliptic: [ '6.5.2' ],
41 silly audit   'escape-string-regexp': [ '1.0.5' ],
41 silly audit   'fs.realpath': [ '1.0.0' ],
41 silly audit   glob: [ '7.1.1' ],
41 silly audit   'graceful-readlink': [ '1.0.1' ],
41 silly audit   growl: [ '1.9.2' ],
41 silly audit   'has-flag': [ '1.0.0' ],
41 silly audit   'hash.js': [ '1.1.7' ],
41 silly audit   he: [ '1.1.1' ],
41 silly audit   'hmac-drbg': [ '1.0.1' ],
41 silly audit   inflight: [ '1.0.6' ],
41 silly audit   inherits: [ '2.0.4' ],
41 silly audit   json3: [ '3.3.2' ],
41 silly audit   'lodash._baseassign': [ '3.2.0' ],
41 silly audit   'lodash._basecopy': [ '3.0.1' ],
41 silly audit   'lodash._basecreate': [ '3.0.3' ],
41 silly audit   'lodash._getnative': [ '3.9.1' ],
41 silly audit   'lodash._isiterateecall': [ '3.0.9' ],
41 silly audit   'lodash.create': [ '3.1.1' ],
41 silly audit   'lodash.isarguments': [ '3.1.0' ],
41 silly audit   'lodash.isarray': [ '3.0.4' ],
41 silly audit   'lodash.keys': [ '3.1.2' ],
41 silly audit   'minimalistic-assert': [ '1.0.1' ],
41 silly audit   'minimalistic-crypto-utils': [ '1.0.1' ],
41 silly audit   minimatch: [ '3.0.4' ],
41 silly audit   minimist: [ '0.0.8' ],
41 silly audit   mkdirp: [ '0.5.1' ],
41 silly audit   mocha: [ '3.5.3' ],
41 silly audit   ms: [ '2.0.0' ],
41 silly audit   once: [ '1.4.0' ],
41 silly audit   'path-is-absolute': [ '1.0.1' ],
41 silly audit   should: [ '11.2.1' ],
41 silly audit   'should-equal': [ '1.0.1' ],
41 silly audit   'should-format': [ '3.0.3' ],
41 silly audit   'should-type': [ '1.4.0' ],
41 silly audit   'should-type-adaptors': [ '1.1.0' ],
41 silly audit   'should-util': [ '1.0.1' ],
41 silly audit   'supports-color': [ '3.1.2' ],
41 silly audit   wrappy: [ '1.0.2' ]
41 silly audit }
42 timing reifyNode:node_modules/wrappy Completed in 143ms
43 timing reifyNode:node_modules/once Completed in 142ms
44 timing reifyNode:node_modules/ms Completed in 142ms
45 timing reifyNode:node_modules/path-is-absolute Completed in 143ms
46 timing reifyNode:node_modules/minimalistic-assert Completed in 143ms
47 timing reifyNode:node_modules/lodash.keys Completed in 143ms
48 timing reifyNode:node_modules/lodash.isarray Completed in 143ms
49 timing reifyNode:node_modules/lodash._isiterateecall Completed in 143ms
50 timing reifyNode:node_modules/lodash.create Completed in 143ms
51 timing reifyNode:node_modules/lodash._getnative Completed in 144ms
52 timing reifyNode:node_modules/lodash.isarguments Completed in 144ms
53 timing reifyNode:node_modules/lodash._basecreate Completed in 144ms
54 timing reifyNode:node_modules/lodash._basecopy Completed in 144ms
55 timing reifyNode:node_modules/lodash._baseassign Completed in 144ms
56 timing reifyNode:node_modules/inflight Completed in 143ms
57 timing reifyNode:node_modules/has-flag Completed in 143ms
58 timing reifyNode:node_modules/escape-string-regexp Completed in 143ms
59 timing reifyNode:node_modules/browser-stdout Completed in 144ms
60 timing reifyNode:node_modules/brace-expansion Completed in 144ms
61 timing reifyNode:node_modules/supports-color Completed in 146ms
62 timing reifyNode:node_modules/inherits Completed in 145ms
63 timing reifyNode:node_modules/balanced-match Completed in 145ms
64 timing reifyNode:node_modules/minimatch Completed in 146ms
65 timing reifyNode:node_modules/graceful-readlink Completed in 146ms
66 timing reifyNode:node_modules/fs.realpath Completed in 146ms
67 timing reifyNode:node_modules/brorand Completed in 146ms
68 timing reifyNode:node_modules/should-util Completed in 149ms
69 timing reifyNode:node_modules/growl Completed in 147ms
70 timing reifyNode:node_modules/should-type-adaptors Completed in 149ms
71 timing reifyNode:node_modules/should-type Completed in 150ms
72 timing reifyNode:node_modules/should-equal Completed in 149ms
73 timing reifyNode:node_modules/minimalistic-crypto-utils Completed in 149ms
74 timing reifyNode:node_modules/commander Completed in 149ms
75 timing reifyNode:node_modules/concat-map Completed in 149ms
76 timing reifyNode:node_modules/should-format Completed in 151ms
77 timing reifyNode:node_modules/json3 Completed in 151ms
78 timing reifyNode:node_modules/hmac-drbg Completed in 150ms
79 timing reifyNode:node_modules/bn.js Completed in 151ms
80 timing reifyNode:node_modules/glob Completed in 151ms
81 timing reifyNode:node_modules/minimist Completed in 153ms
82 timing reifyNode:node_modules/he Completed in 153ms
83 timing reifyNode:node_modules/elliptic/node_modules/bn.js Completed in 154ms
84 timing reifyNode:node_modules/debug Completed in 158ms
85 timing reifyNode:node_modules/hash.js Completed in 160ms
86 timing reifyNode:node_modules/mkdirp Completed in 161ms
87 timing reifyNode:node_modules/should Completed in 162ms
88 timing reifyNode:node_modules/elliptic Completed in 161ms
89 timing reifyNode:node_modules/diff Completed in 164ms
90 timing reifyNode:node_modules/mocha Completed in 169ms
91 timing reify:unpack Completed in 170ms
92 timing reify:unretire Completed in 0ms
93 timing build:queue Completed in 6ms
94 timing build:link:node_modules/he Completed in 2ms
95 timing build:link:node_modules/mkdirp Completed in 2ms
96 timing build:link:node_modules/mocha Completed in 2ms
97 timing build:link Completed in 2ms
98 timing build:deps Completed in 10ms
99 timing build Completed in 10ms
100 timing reify:build Completed in 10ms
101 timing reify:trash Completed in 0ms
102 timing reify:save Completed in 16ms
103 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 387ms
104 timing auditReport:getReport Completed in 389ms
105 silly audit report {
105 silly audit report   growl: [
105 silly audit report     {
105 silly audit report       id: 146,
105 silly audit report       url: 'https://npmjs.com/advisories/146',
105 silly audit report       title: 'Command Injection',
105 silly audit report       severity: 'critical',
105 silly audit report       vulnerable_versions: '<1.10.2'
105 silly audit report     }
105 silly audit report   ],
105 silly audit report   debug: [
105 silly audit report     {
105 silly audit report       id: 534,
105 silly audit report       url: 'https://npmjs.com/advisories/534',
105 silly audit report       title: 'Regular Expression Denial of Service',
105 silly audit report       severity: 'low',
105 silly audit report       vulnerable_versions: '<= 2.6.8 || >= 3.0.0 <= 3.0.1'
105 silly audit report     }
105 silly audit report   ],
105 silly audit report   minimist: [
105 silly audit report     {
105 silly audit report       id: 1179,
105 silly audit report       url: 'https://npmjs.com/advisories/1179',
105 silly audit report       title: 'Prototype Pollution',
105 silly audit report       severity: 'low',
105 silly audit report       vulnerable_versions: '<0.2.1 || >=1.0.0 <1.2.3'
105 silly audit report     }
105 silly audit report   ],
105 silly audit report   elliptic: [
105 silly audit report     {
105 silly audit report       id: 1547,
105 silly audit report       url: 'https://npmjs.com/advisories/1547',
105 silly audit report       title: 'Signature Malleability',
105 silly audit report       severity: 'high',
105 silly audit report       vulnerable_versions: '<6.5.3'
105 silly audit report     },
105 silly audit report     {
105 silly audit report       id: 1648,
105 silly audit report       url: 'https://npmjs.com/advisories/1648',
105 silly audit report       title: 'Use of a Broken or Risky Cryptographic Algorithm',
105 silly audit report       severity: 'moderate',
105 silly audit report       vulnerable_versions: '<6.5.4'
105 silly audit report     }
105 silly audit report   ],
105 silly audit report   diff: [
105 silly audit report     {
105 silly audit report       id: 1631,
105 silly audit report       url: 'https://npmjs.com/advisories/1631',
105 silly audit report       title: 'Regular Expression Denial of Service',
105 silly audit report       severity: 'high',
105 silly audit report       vulnerable_versions: '<3.5.0'
105 silly audit report     }
105 silly audit report   ]
105 silly audit report }
106 timing metavuln:cache:get:security-advisory:growl:6XCw6BoYytDE71iO6yTxDOptfanPuN2b4M0I4hA0DBcEFiMCinsKbWLZ80nCQf4ChkzyIPXaNol2vZx08RMrQQ== Completed in 21ms
107 timing metavuln:cache:get:security-advisory:debug:c/EpWYcLqpggMauDEqU7tsEO/tHyEILe760kXcHD/9HAZjVLK249B6/U6G+d9ROTtaLwElI+G0NkpJJoLNd3sQ== Completed in 16ms
108 timing metavuln:cache:get:security-advisory:minimist:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 15ms
109 timing metavuln:cache:get:security-advisory:elliptic:6a88ftS3QlPrIXzXiAmcmOYqWBXFgREIu46lbxx1q9+cYR+ysRvM94KM8z59hP1zTF0GxLfSunbrTyidA4zUBA== Completed in 14ms
110 timing metavuln:cache:get:security-advisory:elliptic:btR5p+ua0BhQ30g7sWetbVqtdIN+bZG3CSA1PMeIZhIsKaoDgLMyoNJqFMpUpBXjGRfJBpCBz0bOqe23mAviNg== Completed in 13ms
111 timing metavuln:cache:get:security-advisory:diff:jyaxcXiG/Si8JbPB2uQQNPirCQZoIkPG8XC7ZRlFapI+98qR4TIu+wxwa3doVrcC7BqSmr7bQ27QSCxD85CNag== Completed in 13ms
112 http fetch GET 200 https://registry.npmjs.org/minimist 26ms (cache hit)
113 timing metavuln:packument:minimist Completed in 26ms
114 timing metavuln:load:security-advisory:minimist:1179 Completed in 1ms
115 timing metavuln:calculate:security-advisory:minimist:1179 Completed in 27ms
116 http fetch GET 200 https://registry.npmjs.org/debug 28ms (cache hit)
117 timing metavuln:packument:debug Completed in 29ms
118 timing metavuln:load:security-advisory:debug:534 Completed in 1ms
119 timing metavuln:calculate:security-advisory:debug:534 Completed in 31ms
120 http fetch GET 200 https://registry.npmjs.org/growl 31ms (cache hit)
121 timing metavuln:packument:growl Completed in 35ms
122 timing metavuln:load:security-advisory:growl:146 Completed in 0ms
123 timing metavuln:calculate:security-advisory:growl:146 Completed in 37ms
124 http fetch GET 200 https://registry.npmjs.org/elliptic 29ms (cache hit)
125 timing metavuln:packument:elliptic Completed in 29ms
126 timing metavuln:load:security-advisory:elliptic:1547 Completed in 1ms
127 timing metavuln:calculate:security-advisory:elliptic:1547 Completed in 30ms
128 timing metavuln:load:security-advisory:elliptic:1648 Completed in 1ms
129 timing metavuln:calculate:security-advisory:elliptic:1648 Completed in 30ms
130 http fetch GET 200 https://registry.npmjs.org/diff 29ms (cache hit)
131 timing metavuln:packument:diff Completed in 31ms
132 timing metavuln:load:security-advisory:diff:1631 Completed in 0ms
133 timing metavuln:calculate:security-advisory:diff:1631 Completed in 31ms
134 timing metavuln:cache:get:security-advisory:mocha:gfUFB6Qor0XTIOFm0wH/i1fED5VGH7m/OebG1AM8aAmOo/20KEOLVwVkBTfOBVVaqNwMTwq7oFjWZGASatsLhA== Completed in 1ms
135 http fetch GET 200 https://registry.npmjs.org/mocha 2ms (cache hit)
136 timing metavuln:packument:mocha Completed in 6ms
137 timing command:install Completed in 527ms
138 verbose stack TypeError: semver.simplifyRange is not a function
138 verbose stack     at Advisory.[calculateRange] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:191:16)
138 verbose stack     at Advisory.load (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
138 verbose stack     at Calculator.[calculate] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
138 verbose stack     at async Promise.all (index 0)
138 verbose stack     at async Map.[init] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:180:7)
138 verbose stack     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:108:7)
138 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:141:5)
138 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:150:5)
139 verbose cwd /tmp/xfs-9c036f85
140 verbose Linux 5.12.13-arch1-2
141 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
142 verbose node v16.4.0
143 verbose npm  v7.17.0
144 error semver.simplifyRange is not a function
145 verbose exit 1
```

**Comment by NukeManDan** [comment]
I think this is a yarn version issue, are you using yarn v2 and above?

**Comment by gww-parity** [comment]
Yes , my `yarn` is 1.22.10-1 ,as it's the only one that I have in official repositories:

https://archlinux.org/packages/?q=yarn

I followed instructions in this repository README.me .

As it refers to yarnpkg.com, I followed their installation guidelines,
https://yarnpkg.com/getting-started/install

```
Updating to the latest versions
Should you later want to update Yarn to the latest version, just run:

yarn set version latest
```

so I executed:

```
$ yarn set version latest
Resolving latest to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-1.22.10.js...
Saving it into /.yarn/releases/yarn-1.22.10.cjs...
error Could not write file "/yarn-error.log": "EACCES: permission denied, open '/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/.yarn'".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

so again with sudo:

```
$ sudo yarn set version latest
[sudo] password for gw: 
Resolving latest to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-1.22.10.js...
Saving it into /.yarn/releases/yarn-1.22.10.cjs...
Updating //.yarnrc...
Done!
```

to see again:

```
$ yarn -v
1.22.10
```

**Comment by gww-parity** [comment]
Ok, I've tried following and still fails:

```
$ yarn set version berry
$ yarn -v
2.4.2
```

```
$ yarn install
(...)
(exit code 1, logs can be found here: /tmp/xfs-2abfb316/pack.log)
➤ YN0000: └ Completed in 3s 460ms
➤ YN0000: Failed with errors in 4s
```

so 

```
$ cat /tmp/xfs-2abfb316/pack.log
Installing the project using npm

npm ERR! semver.simplifyRange is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-07-01T11_30_16_728Z-debug.log
...

so 

```
$ cat /home/user/.npm/_logs/2021-07-01T11_30_16_728Z-debug.log
...
```

returns similar looking result.

**Comment by gww-parity** [comment]
For clarity, all following attempts fail:

```
$ yarn set version berry
$ yarn -v
2.4.0
$ yarn cache clean ; yarn install
$ yarn cache clean; rm -rf ~/.yarn ~/.npm ; yarn install
```

**Comment by gww-parity** [comment]
Ok, I am not js dev, I have no clue what's wrong with npm and yarn that updating/clearing cache nothing helps,

whoever, when I made clean system setup in Docker it worked.

So let me share Dockerfile: https://gist.github.com/gww-parity/7f0322afb06bbbb99ba2ed544edde04b

commands how to use it are in file comments.

**Comment by TomaszWaszczyk** [comment]
I can confirm that having the versions all works fine:

```
tomek@rhei-box:~/workspaces/substrate-front-end-template$ node -v
v12.22.4
tomek@rhei-box:~/workspaces/substrate-front-end-template$ yarn -v
2.4.0
```

**Comment by Cscotttaakan** [comment]
I have tried using the above and `yarn install` still gives

```
bip32-ed25519@https://github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: The remote archive doesn't match the expected checksum
```

**Comment by NukeManDan** [comment]
node version v12.22.3 is too old. We need at a minimum latest stable.

I found that using present master (now v3.0.0+monthly-2021-09+1) with these versions worked as expected:
- node v14.17.0
- yarn 2.4.0
- npm 7.24.0

**Comment by kauly** [comment]
the problem still persist and the solution is delete the cloned `yarn.lock`.
