### ISSUE TITLE
Trouble Registering Events in Substrate Tutorial's Frontend Transaction: Need Assistance

### ISSUE THREAD

**Issue by frozenmafia** [substrate-developer-hub/substrate-front-end-template#281]
I'm a beginner following the Substrate tutorial from here. After successfully compiling both the Substrate node and frontend, I've encountered an issue.

**Problem:**
When I open the frontend and attempt to make a transaction, it seemingly sends money but fails to register any events. Unlike other tutorials where transactions are instantaneous, I'm facing this discrepancy.

**Screenshot:**
Here's a visual representation of the problem: [![No event registered.][1]][1]

**Error Message:**
Upon clicking the submit button, I receive the following error in the console:

    Uncaught (in promise) TypeError: u.tx[y][m] is not a function
        at M (TxButton.js:105:27)
        at async Object.onClick (TxButton.js:174:5)

**Request:**
I'm seeking guidance on identifying the root cause of this issue and resolving it. Any insights or suggestions on debugging steps or potential solutions would be greatly appreciated. Thank you in advance for your assistance!

  [1]: https://i.sstatic.net/Cby2AoUr.png

**Comment by invent360** [comment]
rename transfer to transferAllowDeath in the transfer.js file. 
Solution is [here](https://github.com/substrate-developer-hub/substrate-front-end-template/issues/279)

**Comment by fzeeshan** [comment]
use my repo it has the fix @frozenmafia
